const { User } = require("../model");
const { hashPassword } = require("../utils/hashPassword");

exports.getUsers = async (req, res) => {
  try {
    var users = await User.find({}).select("-hashedPassword").select("-__v");
    res.status(200).json(users);
  } catch (error) {
    console.error({ messsage: "Something went wrong ðŸ’€", error: error });
    res.status(500).json({ messsage: "Something went wrong ðŸ’€" });
  }
};

exports.getUser = async (req, res) => {
  try {
    const { userId } = req.body;
    var user = await User.findById(userId)
      .select("-hashedPassword")
      .select("-__v");
    res.status(200).json(user);
  } catch (error) {
    console.error({ messsage: "Something went wrong ðŸ’€", error: error });
    res.status(500).json({ messsage: "Something went wrong ðŸ’€" });
  }
};

exports.addUser = async (req, res) => {
  try {
    const { password, email, mobile } = req.body;
    delete req.body.password;
    var user = await User.findOne({ $or: [{ email }, { mobile }] });
    if (user?.email == req.body.email || user?.mobile == req.body.mobile) {
      res.status(202).json({ message: "User Already Exist" });
      return;
    }
    user = await new User({
      ...req.body,
      hashedPassword: await hashPassword(password),
    }).save();
    user = { ...user._doc };
    delete user.__v;
    delete user.hashedPassword;
    res.status(200).json(user);
  } catch (error) {
    console.error({ messsage: "Something went wrong ðŸ’€", error: error });
    res.status(500).json({ messsage: "Something went wrong ðŸ’€" });
  }
};

exports.updateProfile = async (req, res) => {
  try {
    const { email, mobile, firstName, lastName, currentAddress } = req.body;
    const userExists = await User.findOne({
      $or: [{ email }, { mobile }],
    });
    if (userExists?.mobile == mobile || userExists?.email == email) {
      res.status(202).json({ message: "User Already Exist" });
      return;
    }
    var user = await User.findByIdAndUpdate(
      req.body.userId,
      { $set: { firstName, lastName, mobile, currentAddress } },
      {
        new: true,
        runValidators: true,
        useFindAndModify: true,
      }
    );
    if (user) {
      res.status(200).json({ messsage: "Successfully Updated âœ…" });
    } else {
      res.status(200).json({ messsage: "Failed to Update ðŸ’”" });
    }
  } catch (error) {
    console.error({ messsage: "Something went wrong ðŸ’€", error: error });
    res.status(500).json({ messsage: "Something went wrong ðŸ’€" });
  }
};

exports.addAddress = async (req, res) => {
  try {
    const { userId, address } = req.body;
    var user = await User.findByIdAndUpdate(
      userId,
      { $push: { address: address } },
      {
        new: true,
        runValidators: true,
        useFindAndModify: true,
      }
    );
    console.log(user);
    if (user) {
      res.status(200).json({ messsage: "Successfully Updated âœ…" });
    } else {
      res.status(200).json({ messsage: "Failed to Update ðŸ’”" });
    }
  } catch (error) {
    console.error({ messsage: "Something went wrong ðŸ’€", error: error });
    res.status(500).json({ messsage: "Something went wrong ðŸ’€" });
  }
};

exports.updateAddress = async (req, res) => {
  try {
    const { userId, addressId, address } = req.body;
    var user = undefined;
    if (user.modifiedCount > 0) {
      res.status(200).json({ messsage: "Successfully Updated âœ…" });
    } else {
      res.status(200).json({ messsage: "Failed to Update ðŸ’”" });
    }
  } catch (error) {
    console.error({ messsage: "Something went wrong ðŸ’€", error: error });
    res.status(500).json({ messsage: "Something went wrong ðŸ’€" });
  }
};

exports.removeUser = async (req, res) => {
  try {
    var user = await User.findByIdAndRemove(req.body.userId);
    if (user) {
      res.status(200).json({ messsage: "Successfully Removed âœ…" });
    } else {
      res.status(200).json({ messsage: "Failed to Delete ðŸ’”" });
    }
  } catch (error) {
    console.error({ messsage: "Something went wrong ðŸ’€", error: error });
    res.status(500).json({ messsage: "Something went wrong ðŸ’€" });
  }
};
